#!/usr/bin/env python3
"""
Post-processing for Experiment 1: Eigenvalue migration vs gain ratio.

Reads logs/exp1_eig_migration.csv and produces:
  1) Complex-plane plot of eigenvalues colored by gamma (root-locus style).
  2) Plot of max Re(lambda) vs gamma.

Save figures into figures/stability/.
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Path to CSV generated by experiment1_eig_migration.py
CSV_PATH = os.path.join("logs", "exp1_eig_migration.csv")
OUT_DIR = os.path.join("figures", "stability")


def main():
    os.makedirs(OUT_DIR, exist_ok=True)

    df = pd.read_csv(CSV_PATH)

    # Sanity check
    print(df.head())

    # ------------------------------------------------------
    # 1) Complex-plane eigenvalue plot (root-locus style)
    # ------------------------------------------------------
    plt.figure(figsize=(7, 6))
    sc = plt.scatter(
        df["lambda_real"],
        df["lambda_imag"],
        c=df["gamma"],
        cmap="viridis",
        s=20,
        alpha=0.9,
        edgecolors="none",
    )
    plt.axvline(0.0, color="white", linewidth=1.0, linestyle="--")
    plt.axhline(0.0, color="white", linewidth=0.5, linestyle=":")

    cbar = plt.colorbar(sc)
    cbar.set_label(r"Gain ratio $\gamma = k_{\mathrm{attr}}/k_{\mathrm{rep}}$")

    plt.xlabel(r"$\Re(\lambda)$")
    plt.ylabel(r"$\Im(\lambda)$")
    plt.title("Experiment 1: Eigenvalue migration vs gain ratio")
    plt.grid(True, which="both", linestyle=":", alpha=0.3)
    plt.tight_layout()

    out_path1 = os.path.join(OUT_DIR, "exp1_eig_migration_root_locus.png")
    plt.savefig(out_path1, dpi=200)
    print(f"[Saved] {out_path1}")

    # ------------------------------------------------------
    # 2) Max Re(lambda) vs gamma (stability margin)
    # ------------------------------------------------------
    # We stored lambda_max_real once per eigen-set; take unique per run+gamma
    df_summary = (
        df[["run_id", "gamma", "lambda_max_real"]]
        .drop_duplicates()
        .sort_values("gamma")
    )

    plt.figure(figsize=(6, 4))
    plt.plot(
        df_summary["gamma"],
        df_summary["lambda_max_real"],
        marker="o"
    )
    plt.axhline(0.0, color="k", linestyle="--", linewidth=1.0)

    plt.xscale("log")
    plt.xlabel(r"Gain ratio $\gamma = k_{\mathrm{attr}}/k_{\mathrm{rep}}$ (log scale)")
    plt.ylabel(r"$\max_k \Re(\lambda_k)$")
    plt.title("Experiment 1: Stability margin vs gain ratio")
    plt.grid(True, which="both", linestyle=":", alpha=0.4)
    plt.tight_layout()

    out_path2 = os.path.join(OUT_DIR, "exp1_lambda_max_vs_gamma.png")
    plt.savefig(out_path2, dpi=200)
    print(f"[Saved] {out_path2}")


if __name__ == "__main__":
    main()
